## 4. Wrap Up

Every journey comes to and end. Now you know how to use JSON-LD and GeoJSON-LD files.

What is it? It is time to sum up!

In the first section a quick introduction to the course was given. We firstly explained how JSON files work. We showed that JSON is basically a way to interchange data and that is structured in a way that both machine and humans can understand.

Knowing most of the concepts about JSON, it was time to learn about GeoJSON, the differences between both files were presented. You were able to see that GeoJSON follows one structure really similar to the JSON, but considering special objects to represent geographical data (also known as `Point`, `LineString`, `Polygon`, `MultiPoint`, `MultiPolygon`, `GeometryCollection`).

With a good foundation, we were finally able to start learning about the JSON-LD and GeoJSON-LD. You learned the concept of linked data and together with it, you learned how to use the special structures that define the JSON-LD and GeoJSON-LD files (aka `@context` and `@type`).

After reading, seeing some videos, coding with the code snippets and finally answering quiz questions, you are now in the group of people that know how to use JSON-LD and GeoJSON-LD. Congrats my friend!

Remember, practicing is always the best way to learn something. Keep practicing the concepts that you learned.

One more thing, this module was developed to help the most number of people possible. Share this resource with your friends that you believe would want to learn about JSON-LD and GeoJSON-LD.

Do you have any advice or suggestions? Our [GitHub](https://github.com/LukasBaecker/geoJSON-LD_OER-module) page is also there to help you.

```{r struturePic2, echo=FALSE, out.width= "100%", out.extra='style="float:right; padding:10px"'}
myimg10 <- load.image("graphics/undraw_Well_done_re_3hpo.png")
grid.raster(myimg10)
```







