---
title: "part2_understandingJSON_GEOJSON"
output:
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: >
  Learn how to set up R and RStudio on your machine. We will also demonstrate
  how to install R packages from CRAN, and install the tidyverse package.
---
##   2.2. GeoJSON
```{r geopic, echo=FALSE, out.width= "65%", out.extra='style="float:right; padding:10px"'}
geoimg <- load.image("graphics/undraw_real_time_analytics_re_yliv.png")
grid.raster(geoimg)
```
GeoJSON is the JSON specialization for storing geographical data data. Additional to the JSON rules there are some more that defines a GeoJSON. A GeoJSON has to have a 'type' attribute than can be a value of these: [`Point`, `MultiPoint`, `LineString`, `MultiLineString`, `Polygon`, `MultiPolygon`, `GeometryCollection`, `Feature`, `FeatureCollection`]. Furthermore the position is important for a GeoJSON where coordinates are allway given in `WGS84` due to the fact that other CRS harm the interoperability of the GeoJSON.
Below you can see the official definition from [GeoJSON.org](https://geojson.org/):
::: {#GeoJSONdefinition .message}
GeoJSON is a format for encoding a variety of geographic data structures.GeoJSON supports the following geometry types: Point, LineString, Polygon, MultiPoint, MultiLineString, and MultiPolygon. Geometric objects with additional properties are Feature objects. Sets of features are contained by FeatureCollection objects.
:::

Now, lets have a look at an example for a GeoJSON. The first one shows a valid point and the second one a feature with a geometry that is also a point. The difference lays in the structure and the additional information that are included.

A point saved in a GeoJSON as a `Point`:
```json
{
    "type": "Point",
    "coordinates": [125.6, 10.1]
}
```
A point saved as a `Feature` with additional information:
```json
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}

```

Another example shows a regular `MultiPolygon`. It has multiple arrays of points that are also saved inside of arrays. At this point it is important to keep track of the brackets to get not confused and supply the computer with wrong information buy using a wrong structure.
```json
    {
         "type": "MultiPolygon",
         "coordinates": [
             [
                 [
                     [102.0, 2.0],
                     [103.0, 2.0],
                     [103.0, 3.0],
                     [102.0, 3.0],
                     [102.0, 2.0]
                 ]
             ],
             [
                 [
                     [100.0, 0.0],
                     [101.0, 0.0],
                     [101.0, 1.0],
                     [100.0, 1.0],
                     [100.0, 0.0]
                 ],
                 [
                     [100.2, 0.2],
                     [100.2, 0.8],
                     [100.8, 0.8],
                     [100.8, 0.2],
                     [100.2, 0.2]
                 ]
             ]
         ]
     }

```
I you want to read the whole GeoJSON specification you can [follow this link to the GeoJSON specification (RFC 7946)](https://datatracker.ietf.org/doc/html/rfc7946)

POSSIBLE QUESTIONS AT THE END:
what do we see in a code snipped 
what is legal or illigal with geojson 

If you would like to see the official definition of GeoJSON you may have [a look at this page](https://datatracker.ietf.org/doc/html/rfc7946).

TODO: NOCHMAL DETAILIERTER BESCHREIBEN UND SCHRITT FÜR SCHRITT ERKLÄREN WIE NE GEOJSON AUFGEBAUT IST
